# Generated by Django 2.0.6 on 2018-06-06 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientOrganization',
        ),
    ]
